name: build
on:
  push:
    branches:
      - generics
    paths:
      - '**.go'
  pull_request:
    branches:
      - generics
    paths:
      - '**.go'
jobs:
  test:
    name: Test with coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Run tests
        run: go test -race -coverprofile=coverage.txt -coverpkg=./... ./...
      - name: Send coverage
        uses: codecov/codecov-action@v2
