name: build
on:
  push:
    branches:
      - generics
    paths:
      - '**.go'
  pull_request:
    branches:
      - generics
    paths:
      - '**.go'
jobs:
  build:
    name: Test with coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Run tests
        run: go test -race -coverprofile=profile.cov -coverpkg=./... ./...
      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
